### ISSUE TITLE
What is our project going to be?

### ISSUE THREAD

**Issue by NBP77** [NBP77/Project-2#1]
Brainstorm!!!

**Comment by jareddeuriarte** [comment]
i'm just spitballing, thinking of my user experience with music and aspects about it that could be enhanced....

Friends and I constantly share songs back and forth that we want the other to listen to, but I never get around to actually listening to any of the suggestions once they're lost in the text thread. So I was thinking....rather than tossing a song in the group chat only to be quickly lost an forgotten about, maybe it would be cool to have a place where friends can post "songs I think my friends should be listening to" and in effect it creates a playlist. Maybe you make different playlists for different friends? There's a cute, personal dimension about it because they're all the songs your friend picked specifically for you. 

There needs to be some kind of hook, importantly though, because obviously everyone already has the capability of creating their own playlist in Spotify/apple music/pandora and sharing that playlist with a friend. This is mainly food for thought, and maybe there's something in it that we can elaborate on.

**Comment by tfletch3018** [comment]
completed
